[build]
  base = "packages/"
  command = "npm install && npm run build"
  functions = "packages/server/netlify-lambda"
  publish = "packages/client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
