[build]
  base = "packages/"
  command = "npm install && npm run build"
  functions = "server/netlify-lambda"
  publish = "client/build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/graphql"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
